### ISSUE TITLE
The date

### ISSUE THREAD

**Issue by SofiiaRomah** [SofiiaRomah/Trip#1]

**Comment by SofiiaRomah** [comment]
I know that the best time to go to Iceland is in late September.

**Comment by SofiiaRomah** [comment]
Would you mind if I look for tickets in that time? @natalicka

**Comment by natalicka** [comment]
Ok, i agree with you)

**Comment by SofiiaRomah** [comment]
Ok, but there are no direct flights from Lviv to Reykjavik. And the best idea is to fly through Amsterdam/ Will it be ok?

**Comment by natalicka** [comment]
Ok, its great choice!!!

**Comment by natalicka** [comment]
Lets fly 25 September there and 27 September we can fly back

**Comment by SofiiaRomah** [comment]
Nice idea!
