### ISSUE TITLE
Tickets

### ISSUE THREAD

**Issue by natalicka** [SofiiaRomah/Trip#2]
Tickets there and back

**Comment by SofiiaRomah** [comment]
I have already find tickets in one way. Here they are:
[Amsterdam-Reykjavik_Natalia.txt](https://github.com/SofiiaRomah/Trip/files/3074949/Amsterdam-Reykjavik_Natalia.txt)
[Amsterdam-Reykjavik_Sofiia.txt](https://github.com/SofiiaRomah/Trip/files/3074950/Amsterdam-Reykjavik_Sofiia.txt)
[Lviv-Amsterdam_Natalia.txt](https://github.com/SofiiaRomah/Trip/files/3074951/Lviv-Amsterdam_Natalia.txt)
[Lviv-Amsterdam_Sofiia.txt](https://github.com/SofiiaRomah/Trip/files/3074952/Lviv-Amsterdam_Sofiia.txt)

**Comment by SofiiaRomah** [comment]
Also I find tickets back. The total cost for all tickets is 200 euro per person.

**Comment by SofiiaRomah** [comment]
[Amsterdam-Lviv_Natalia.txt](https://github.com/SofiiaRomah/Trip/files/3074976/Amsterdam-Lviv_Natalia.txt)
[Amsterdam-Lviv_Sofiia.txt](https://github.com/SofiiaRomah/Trip/files/3074977/Amsterdam-Lviv_Sofiia.txt)
[Reykjavik-Amsterdam_Natalia.txt](https://github.com/SofiiaRomah/Trip/files/3074978/Reykjavik-Amsterdam_Natalia.txt)
[Reykjavik-Amsterdam_Sofiia.txt](https://github.com/SofiiaRomah/Trip/files/3074979/Reykjavik-Amsterdam_Sofiia.txt)
