### ISSUE TITLE
Transport

### ISSUE THREAD

**Issue by SofiiaRomah** [SofiiaRomah/Trip#4]
We have to choose on which transport we will move during all over small trips.

**Comment by natalicka** [comment]
I think it make sense to buy travel pass for all transport

**Comment by SofiiaRomah** [comment]
It is great idea, I find that there is travel pass for 7 day, for 20euro per person

**Comment by natalicka** [comment]
Can we buy it there?

**Comment by SofiiaRomah** [comment]
Yes, of course. I find a lot of places where we can buy this passes))
