### ISSUE TITLE
Places to visit

### ISSUE THREAD

**Issue by SofiiaRomah** [SofiiaRomah/Trip#5]
There are so many places in Iceland we must see!

**Comment by natalicka** [comment]
Ohh yee)I find some nice places to visit
https://guidetoiceland.is/nature-info/what-to-do-in-iceland
What do u think?

**Comment by SofiiaRomah** [comment]
Wow! I am shocked how its fascinating! I want to go there as soon as possible)

**Comment by SofiiaRomah** [comment]
Also I have found some interesting and breathtaking places in Reykjavik to see. Hope you will like it=)
https://guidetoiceland.is/reykjavik-guide/top-10-things-to-do-in-reykjavik

**Comment by SofiiaRomah** [comment]
Just look on this paradise!
![42-68235492](https://user-images.githubusercontent.com/36325191/56064699-7eba2600-5d7b-11e9-94c5-90ca3f0e8cb1.jpg)

**Comment by SofiiaRomah** [comment]
![42-68235492](https://user-images.githubusercontent.com/36325191/56064727-9beef480-5d7b-11e9-9960-cf5fcb3120b1.jpg)
Is this real?)))))

**Comment by SofiiaRomah** [comment]
Is this real?))
![iceland-1751463_1920](https://user-images.githubusercontent.com/36325191/56064778-b6c16900-5d7b-11e9-968d-7ea56308aaa0.jpg)

**Comment by SofiiaRomah** [comment]
@natalicka what do you think?

**Comment by natalicka** [comment]
Its marvelous, i cant believe in this)))
